spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 40MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: 


logging:
  level:
    org.springframework: INFO